server:
  port: 8091
  servlet:
      context-path: /api

spring:
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  application:
    name: microservice-produto
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      import-check:
        enabled: false
    kubernetes:
      config:
        name: default-name
        namespace: default-namespace
        sources:
          - name: c1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  file:
    name: Sistema.log

client:
  timeout: 40000
  memory-size: 2000000